### PR TITLE
Update events.csv

### PR DESCRIPTION
**Pull request by Jorieke**

### CODE REVIEW

**Comment by Jorieke** [comment]
Seems like some of the events I recently uploaded, do not appear on the listing on the website (the 3 last ones: Czec Republic Ostrava, Ghana and Argentina). 
Also I tried to delete the  « Mapatho avec le soutien de la Région Auvergne-Rhone Alpes », but no success either. 
What did I do wrong? Somebody can help?

**Comment by danbjoseph** [comment]
It's a nightly build process. Not instantaneous. If you need it up urgently, you can ping us to manually restart the website build process. But otherwise it can take up to 24 hours to show up.

**Comment by Jorieke** [comment]
Oh, I thought that it was instantaneous, or at least quicker than 24 hours. So this is good news 👍 I did mess around a bit last days, to much events added recently and all, so I thought I messed it up again. No, not urgent, I check tomorrow again 
Thanks a lot!

**Comment by Jorieke** [comment]
thanks for the reset, it looks good now! :-)

**Pull request merged**
